# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachId', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('coachEmail', models.EmailField(max_length=50, unique=True)),
                ('coachUsername', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachingPlanId', models.IntegerField(unique=True)),
                ('coachingPlanTitle', models.CharField(max_length=20)),
                ('coachingPlanType', models.CharField(max_length=20)),
                ('coachingPlanDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosketch', models.TextField()),
                ('profilePic', models.ImageField(upload_to='')),
                ('profileOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drillId', models.IntegerField(unique=True)),
                ('drillTitle', models.CharField(max_length=20)),
                ('drillImage', models.ImageField(upload_to='')),
                ('drillDescription', models.TextField()),
                ('drillType', models.CharField(max_length=20)),
                ('drillRate', models.IntegerField()),
                ('drillSetup', models.TextField()),
                ('drillInstruction', models.TextField()),
                ('drillDate', models.DateField()),
                ('drillOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineupStyle', models.CharField(max_length=12)),
                ('LineupOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField(unique=True)),
                ('playerJerseyLabel', models.CharField(max_length=3)),
                ('playerGoalCount', models.IntegerField()),
                ('playerYellowCard', models.IntegerField()),
                ('PlayerRedCard', models.BooleanField()),
                ('playersCoach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='LineupPlayers',
            field=models.ManyToManyField(to='GafferApp.Player'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='coachingPlanDrill',
            field=models.ManyToManyField(to='GafferApp.Drill'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='coachingPlanOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.Coach'),
        ),
    ]
